### ISSUE TITLE
fix wrong status for proposals bug

### ISSUE THREAD

**Issue by letmejustputthishere** [flowerpowerdao/fpd#113]
right now, proposals that were actually sucessfull are shown as rejected because we added ICP flowers to the voting count and the threshoold is not met anymore.

**Comment by ZenVoich** [comment]
Bug was in `closeExpiredProposals` func that was calling from `heartbeat` closing already closed proposals.
Need to merge https://github.com/flowerpowerdao/fpd/pull/114 first, deploy, heartbeat will update state for old proposals.
Then merge https://github.com/flowerpowerdao/fpd/pull/115 and deploy, this will prevent already closed offers from closing
